k#!/usr/bin/env python3

import json
import locale
import sys
import operator
import reports
from email.message import EmailMessage
import os.path
import emails



def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  total_sales=0
  car_model=""
  sales_dict={}

  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    if item["total_sales"]>total_sales:
        total_sales=item["total_sales"]
        car_model=item["car"]["car_model"]
        
    sales_dict[item["car"]["car_year"]] = sales_dict.get(item["car"]["car_year"],0)+item["total_sales"]

  max_year = max(sales_dict.items(), key=operator.itemgetter(1))[0]
  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
      
    "The {} had the most sales: {}".format(car_model,total_sales),
      
    "The most popular year was {} with {} sales.".format(max_year, sales_dict[max_year])
  ]
  print(summary)

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # Turn this into a PDF report, Add Tables to our PDFs
  table_data=cars_dict_to_table(data)
  reports.generate("/tmp/cars.pdf", "Sales summary for last month", "{}<br/>{}<br/>{}".format(summary[0],summary[1],summary[2]), table_data)
  
  # Send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = "{}\n{}\n{}".format(summary[0],summary[1],summary[2])
   
  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  emails.send(message)


if __name__ == "__main__":
  main(sys.argv)
   


